/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AddressDetailsProperty
 */
public class AddressDetailsPropertyTest {
    private final AddressDetailsProperty model = new AddressDetailsProperty();

    /**
     * Model tests for AddressDetailsProperty
     */
    @Test
    public void testAddressDetailsProperty() {
        // TODO: test AddressDetailsProperty
    }

    /**
     * Test the property 'streetNumber'
     */
    @Test
    public void streetNumberTest() {
        // TODO: test streetNumber
    }

    /**
     * Test the property 'streetName'
     */
    @Test
    public void streetNameTest() {
        // TODO: test streetName
    }

    /**
     * Test the property 'streetType'
     */
    @Test
    public void streetTypeTest() {
        // TODO: test streetType
    }

    /**
     * Test the property 'deliveryService'
     */
    @Test
    public void deliveryServiceTest() {
        // TODO: test deliveryService
    }

    /**
     * Test the property 'buildingName'
     */
    @Test
    public void buildingNameTest() {
        // TODO: test buildingName
    }

    /**
     * Test the property 'subBuilding'
     */
    @Test
    public void subBuildingTest() {
        // TODO: test subBuilding
    }

}
