/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AddressDetailsProperty1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AddressPortable2
 */
public class AddressPortable2Test {
    private final AddressPortable2 model = new AddressPortable2();

    /**
     * Model tests for AddressPortable2
     */
    @Test
    public void testAddressPortable2() {
        // TODO: test AddressPortable2
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'addressLine3'
     */
    @Test
    public void addressLine3Test() {
        // TODO: test addressLine3
    }

    /**
     * Test the property 'adminArea4'
     */
    @Test
    public void adminArea4Test() {
        // TODO: test adminArea4
    }

    /**
     * Test the property 'adminArea3'
     */
    @Test
    public void adminArea3Test() {
        // TODO: test adminArea3
    }

    /**
     * Test the property 'adminArea2'
     */
    @Test
    public void adminArea2Test() {
        // TODO: test adminArea2
    }

    /**
     * Test the property 'adminArea1'
     */
    @Test
    public void adminArea1Test() {
        // TODO: test adminArea1
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'addressDetails'
     */
    @Test
    public void addressDetailsTest() {
        // TODO: test addressDetails
    }

}
