/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplePayPaymentData;
import com.konfigthis.client.model.Card;
import com.konfigthis.client.model.Money2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplePayDecryptedTokenData
 */
public class ApplePayDecryptedTokenDataTest {
    private final ApplePayDecryptedTokenData model = new ApplePayDecryptedTokenData();

    /**
     * Model tests for ApplePayDecryptedTokenData
     */
    @Test
    public void testApplePayDecryptedTokenData() {
        // TODO: test ApplePayDecryptedTokenData
    }

    /**
     * Test the property 'transactionAmount'
     */
    @Test
    public void transactionAmountTest() {
        // TODO: test transactionAmount
    }

    /**
     * Test the property 'tokenizedCard'
     */
    @Test
    public void tokenizedCardTest() {
        // TODO: test tokenizedCard
    }

    /**
     * Test the property 'deviceManufacturerId'
     */
    @Test
    public void deviceManufacturerIdTest() {
        // TODO: test deviceManufacturerId
    }

    /**
     * Test the property 'paymentDataType'
     */
    @Test
    public void paymentDataTypeTest() {
        // TODO: test paymentDataType
    }

    /**
     * Test the property 'paymentData'
     */
    @Test
    public void paymentDataTest() {
        // TODO: test paymentData
    }

}
