/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LiabilityShift;
import com.konfigthis.client.model.ThreeDSecureAuthenticationResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthenticationResponse
 */
public class AuthenticationResponseTest {
    private final AuthenticationResponse model = new AuthenticationResponse();

    /**
     * Model tests for AuthenticationResponse
     */
    @Test
    public void testAuthenticationResponse() {
        // TODO: test AuthenticationResponse
    }

    /**
     * Test the property 'liabilityShift'
     */
    @Test
    public void liabilityShiftTest() {
        // TODO: test liabilityShift
    }

    /**
     * Test the property 'threeDSecure'
     */
    @Test
    public void threeDSecureTest() {
        // TODO: test threeDSecure
    }

    /**
     * Test the property 'authenticationFlow'
     */
    @Test
    public void authenticationFlowTest() {
        // TODO: test authenticationFlow
    }

    /**
     * Test the property 'exemptionDetails'
     */
    @Test
    public void exemptionDetailsTest() {
        // TODO: test exemptionDetails
    }

}
