/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BinDetails
 */
public class BinDetailsTest {
    private final BinDetails model = new BinDetails();

    /**
     * Model tests for BinDetails
     */
    @Test
    public void testBinDetails() {
        // TODO: test BinDetails
    }

    /**
     * Test the property 'bin'
     */
    @Test
    public void binTest() {
        // TODO: test bin
    }

    /**
     * Test the property 'issuingBank'
     */
    @Test
    public void issuingBankTest() {
        // TODO: test issuingBank
    }

    /**
     * Test the property 'binCountryCode'
     */
    @Test
    public void binCountryCodeTest() {
        // TODO: test binCountryCode
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

}
