/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BlikExperienceContext
 */
public class BlikExperienceContextTest {
    private final BlikExperienceContext model = new BlikExperienceContext();

    /**
     * Model tests for BlikExperienceContext
     */
    @Test
    public void testBlikExperienceContext() {
        // TODO: test BlikExperienceContext
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'shippingPreference'
     */
    @Test
    public void shippingPreferenceTest() {
        // TODO: test shippingPreference
    }

    /**
     * Test the property 'returnUrl'
     */
    @Test
    public void returnUrlTest() {
        // TODO: test returnUrl
    }

    /**
     * Test the property 'cancelUrl'
     */
    @Test
    public void cancelUrlTest() {
        // TODO: test cancelUrl
    }

    /**
     * Test the property 'consumerIp'
     */
    @Test
    public void consumerIpTest() {
        // TODO: test consumerIp
    }

    /**
     * Test the property 'consumerUserAgent'
     */
    @Test
    public void consumerUserAgentTest() {
        // TODO: test consumerUserAgent
    }

}
