/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BlikOneClickResponse
 */
public class BlikOneClickResponseTest {
    private final BlikOneClickResponse model = new BlikOneClickResponse();

    /**
     * Model tests for BlikOneClickResponse
     */
    @Test
    public void testBlikOneClickResponse() {
        // TODO: test BlikOneClickResponse
    }

    /**
     * Test the property 'consumerReference'
     */
    @Test
    public void consumerReferenceTest() {
        // TODO: test consumerReference
    }

}
