/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BlikOneClick
 */
public class BlikOneClickTest {
    private final BlikOneClick model = new BlikOneClick();

    /**
     * Model tests for BlikOneClick
     */
    @Test
    public void testBlikOneClick() {
        // TODO: test BlikOneClick
    }

    /**
     * Test the property 'authCode'
     */
    @Test
    public void authCodeTest() {
        // TODO: test authCode
    }

    /**
     * Test the property 'consumerReference'
     */
    @Test
    public void consumerReferenceTest() {
        // TODO: test consumerReference
    }

    /**
     * Test the property 'aliasLabel'
     */
    @Test
    public void aliasLabelTest() {
        // TODO: test aliasLabel
    }

    /**
     * Test the property 'aliasKey'
     */
    @Test
    public void aliasKeyTest() {
        // TODO: test aliasKey
    }

}
