/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Level2CardProcessingData;
import com.konfigthis.client.model.Level3CardProcessingData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardSupplementaryData
 */
public class CardSupplementaryDataTest {
    private final CardSupplementaryData model = new CardSupplementaryData();

    /**
     * Model tests for CardSupplementaryData
     */
    @Test
    public void testCardSupplementaryData() {
        // TODO: test CardSupplementaryData
    }

    /**
     * Test the property 'level2'
     */
    @Test
    public void level2Test() {
        // TODO: test level2
    }

    /**
     * Test the property 'level3'
     */
    @Test
    public void level3Test() {
        // TODO: test level3
    }

}
