/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CardExperienceContext;
import com.konfigthis.client.model.CardStoredCredential;
import com.konfigthis.client.model.NetworkTokenRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardRequestAllOf
 */
public class CardRequestAllOfTest {
    private final CardRequestAllOf model = new CardRequestAllOf();

    /**
     * Model tests for CardRequestAllOf
     */
    @Test
    public void testCardRequestAllOf() {
        // TODO: test CardRequestAllOf
    }

    /**
     * Test the property 'vaultId'
     */
    @Test
    public void vaultIdTest() {
        // TODO: test vaultId
    }

    /**
     * Test the property 'storedCredential'
     */
    @Test
    public void storedCredentialTest() {
        // TODO: test storedCredential
    }

    /**
     * Test the property 'networkToken'
     */
    @Test
    public void networkTokenTest() {
        // TODO: test networkToken
    }

    /**
     * Test the property 'experienceContext'
     */
    @Test
    public void experienceContextTest() {
        // TODO: test experienceContext
    }

}
