/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NetworkTransactionReference;
import com.konfigthis.client.model.PaymentInitiator;
import com.konfigthis.client.model.StoredPaymentSourcePaymentType;
import com.konfigthis.client.model.StoredPaymentSourceUsageType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardStoredCredential
 */
public class CardStoredCredentialTest {
    private final CardStoredCredential model = new CardStoredCredential();

    /**
     * Model tests for CardStoredCredential
     */
    @Test
    public void testCardStoredCredential() {
        // TODO: test CardStoredCredential
    }

    /**
     * Test the property 'paymentInitiator'
     */
    @Test
    public void paymentInitiatorTest() {
        // TODO: test paymentInitiator
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'previousNetworkTransactionReference'
     */
    @Test
    public void previousNetworkTransactionReferenceTest() {
        // TODO: test previousNetworkTransactionReference
    }

}
