/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AddressPortable;
import com.konfigthis.client.model.LineItem;
import com.konfigthis.client.model.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Level3CardProcessingData
 */
public class Level3CardProcessingDataTest {
    private final Level3CardProcessingData model = new Level3CardProcessingData();

    /**
     * Model tests for Level3CardProcessingData
     */
    @Test
    public void testLevel3CardProcessingData() {
        // TODO: test Level3CardProcessingData
    }

    /**
     * Test the property 'shippingAmount'
     */
    @Test
    public void shippingAmountTest() {
        // TODO: test shippingAmount
    }

    /**
     * Test the property 'dutyAmount'
     */
    @Test
    public void dutyAmountTest() {
        // TODO: test dutyAmount
    }

    /**
     * Test the property 'discountAmount'
     */
    @Test
    public void discountAmountTest() {
        // TODO: test discountAmount
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    public void shippingAddressTest() {
        // TODO: test shippingAddress
    }

    /**
     * Test the property 'shipsFromPostalCode'
     */
    @Test
    public void shipsFromPostalCodeTest() {
        // TODO: test shipsFromPostalCode
    }

    /**
     * Test the property 'lineItems'
     */
    @Test
    public void lineItemsTest() {
        // TODO: test lineItems
    }

}
