/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EciFlag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NetworkTokenRequest
 */
public class NetworkTokenRequestTest {
    private final NetworkTokenRequest model = new NetworkTokenRequest();

    /**
     * Model tests for NetworkTokenRequest
     */
    @Test
    public void testNetworkTokenRequest() {
        // TODO: test NetworkTokenRequest
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'expiry'
     */
    @Test
    public void expiryTest() {
        // TODO: test expiry
    }

    /**
     * Test the property 'cryptogram'
     */
    @Test
    public void cryptogramTest() {
        // TODO: test cryptogram
    }

    /**
     * Test the property 'eciFlag'
     */
    @Test
    public void eciFlagTest() {
        // TODO: test eciFlag
    }

    /**
     * Test the property 'tokenRequestorId'
     */
    @Test
    public void tokenRequestorIdTest() {
        // TODO: test tokenRequestorId
    }

}
