/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ShipmentCarrier;
import com.konfigthis.client.model.ShipmentTrackingNumberType;
import com.konfigthis.client.model.ShipmentTrackingStatus;
import com.konfigthis.client.model.TrackerItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderTrackerRequest
 */
public class OrderTrackerRequestTest {
    private final OrderTrackerRequest model = new OrderTrackerRequest();

    /**
     * Model tests for OrderTrackerRequest
     */
    @Test
    public void testOrderTrackerRequest() {
        // TODO: test OrderTrackerRequest
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'trackingNumber'
     */
    @Test
    public void trackingNumberTest() {
        // TODO: test trackingNumber
    }

    /**
     * Test the property 'trackingNumberType'
     */
    @Test
    public void trackingNumberTypeTest() {
        // TODO: test trackingNumberType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'shipmentDate'
     */
    @Test
    public void shipmentDateTest() {
        // TODO: test shipmentDate
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'carrierNameOther'
     */
    @Test
    public void carrierNameOtherTest() {
        // TODO: test carrierNameOther
    }

    /**
     * Test the property 'postagePaymentId'
     */
    @Test
    public void postagePaymentIdTest() {
        // TODO: test postagePaymentId
    }

    /**
     * Test the property 'notifyBuyer'
     */
    @Test
    public void notifyBuyerTest() {
        // TODO: test notifyBuyer
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'trackingNumberValidated'
     */
    @Test
    public void trackingNumberValidatedTest() {
        // TODO: test trackingNumberValidated
    }

    /**
     * Test the property 'lastUpdatedTime'
     */
    @Test
    public void lastUpdatedTimeTest() {
        // TODO: test lastUpdatedTime
    }

    /**
     * Test the property 'shipmentDirection'
     */
    @Test
    public void shipmentDirectionTest() {
        // TODO: test shipmentDirection
    }

    /**
     * Test the property 'shipmentUploader'
     */
    @Test
    public void shipmentUploaderTest() {
        // TODO: test shipmentUploader
    }

    /**
     * Test the property 'captureId'
     */
    @Test
    public void captureIdTest() {
        // TODO: test captureId
    }

    /**
     * Test the property 'notifyPayer'
     */
    @Test
    public void notifyPayerTest() {
        // TODO: test notifyPayer
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
