/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AuthorizationWithAdditionalData;
import com.konfigthis.client.model.Capture;
import com.konfigthis.client.model.Refund;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentCollection
 */
public class PaymentCollectionTest {
    private final PaymentCollection model = new PaymentCollection();

    /**
     * Model tests for PaymentCollection
     */
    @Test
    public void testPaymentCollection() {
        // TODO: test PaymentCollection
    }

    /**
     * Test the property 'authorizations'
     */
    @Test
    public void authorizationsTest() {
        // TODO: test authorizations
    }

    /**
     * Test the property 'captures'
     */
    @Test
    public void capturesTest() {
        // TODO: test captures
    }

    /**
     * Test the property 'refunds'
     */
    @Test
    public void refundsTest() {
        // TODO: test refunds
    }

}
