/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DisbursementMode;
import com.konfigthis.client.model.PlatformFee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentInstruction
 */
public class PaymentInstructionTest {
    private final PaymentInstruction model = new PaymentInstruction();

    /**
     * Model tests for PaymentInstruction
     */
    @Test
    public void testPaymentInstruction() {
        // TODO: test PaymentInstruction
    }

    /**
     * Test the property 'platformFees'
     */
    @Test
    public void platformFeesTest() {
        // TODO: test platformFees
    }

    /**
     * Test the property 'disbursementMode'
     */
    @Test
    public void disbursementModeTest() {
        // TODO: test disbursementMode
    }

    /**
     * Test the property 'payeePricingTierId'
     */
    @Test
    public void payeePricingTierIdTest() {
        // TODO: test payeePricingTierId
    }

    /**
     * Test the property 'payeeReceivableFxRateId'
     */
    @Test
    public void payeeReceivableFxRateIdTest() {
        // TODO: test payeeReceivableFxRateId
    }

}
