/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Bancontact;
import com.konfigthis.client.model.Blik;
import com.konfigthis.client.model.CardResponse;
import com.konfigthis.client.model.Eps;
import com.konfigthis.client.model.Giropay;
import com.konfigthis.client.model.Ideal;
import com.konfigthis.client.model.Mybank;
import com.konfigthis.client.model.P24;
import com.konfigthis.client.model.PaypalWalletResponse;
import com.konfigthis.client.model.Sofort;
import com.konfigthis.client.model.Trustly;
import com.konfigthis.client.model.VenmoWalletResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentSourceResponse
 */
public class PaymentSourceResponseTest {
    private final PaymentSourceResponse model = new PaymentSourceResponse();

    /**
     * Model tests for PaymentSourceResponse
     */
    @Test
    public void testPaymentSourceResponse() {
        // TODO: test PaymentSourceResponse
    }

    /**
     * Test the property 'card'
     */
    @Test
    public void cardTest() {
        // TODO: test card
    }

    /**
     * Test the property 'paypal'
     */
    @Test
    public void paypalTest() {
        // TODO: test paypal
    }

    /**
     * Test the property 'bancontact'
     */
    @Test
    public void bancontactTest() {
        // TODO: test bancontact
    }

    /**
     * Test the property 'blik'
     */
    @Test
    public void blikTest() {
        // TODO: test blik
    }

    /**
     * Test the property 'eps'
     */
    @Test
    public void epsTest() {
        // TODO: test eps
    }

    /**
     * Test the property 'giropay'
     */
    @Test
    public void giropayTest() {
        // TODO: test giropay
    }

    /**
     * Test the property 'ideal'
     */
    @Test
    public void idealTest() {
        // TODO: test ideal
    }

    /**
     * Test the property 'mybank'
     */
    @Test
    public void mybankTest() {
        // TODO: test mybank
    }

    /**
     * Test the property 'p24'
     */
    @Test
    public void p24Test() {
        // TODO: test p24
    }

    /**
     * Test the property 'sofort'
     */
    @Test
    public void sofortTest() {
        // TODO: test sofort
    }

    /**
     * Test the property 'trustly'
     */
    @Test
    public void trustlyTest() {
        // TODO: test trustly
    }

    /**
     * Test the property 'venmo'
     */
    @Test
    public void venmoTest() {
        // TODO: test venmo
    }

}
