/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Information about the decrypted apple pay payment data for the token like cryptogram, eci indicator.
 */
@ApiModel(description = "Information about the decrypted apple pay payment data for the token like cryptogram, eci indicator.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ApplePayPaymentData {
  public static final String SERIALIZED_NAME_CRYPTOGRAM = "cryptogram";
  @SerializedName(SERIALIZED_NAME_CRYPTOGRAM)
  private String cryptogram;

  public static final String SERIALIZED_NAME_ECI_INDICATOR = "eci_indicator";
  @SerializedName(SERIALIZED_NAME_ECI_INDICATOR)
  private String eciIndicator;

  public static final String SERIALIZED_NAME_EMV_DATA = "emv_data";
  @SerializedName(SERIALIZED_NAME_EMV_DATA)
  private String emvData;

  public static final String SERIALIZED_NAME_PIN = "pin";
  @SerializedName(SERIALIZED_NAME_PIN)
  private String pin;

  public ApplePayPaymentData() {
  }

  public ApplePayPaymentData cryptogram(String cryptogram) {
    
    
    if (cryptogram != null && cryptogram.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cryptogram. Length must be greater than or equal to 1.");
    }
    
    this.cryptogram = cryptogram;
    return this;
  }

   /**
   * Online payment cryptogram, as defined by 3D Secure. The pattern is defined by an external party and supports Unicode.
   * @return cryptogram
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Online payment cryptogram, as defined by 3D Secure. The pattern is defined by an external party and supports Unicode.")

  public String getCryptogram() {
    return cryptogram;
  }


  public void setCryptogram(String cryptogram) {
    
    
    if (cryptogram != null && cryptogram.length() < 1) {
      throw new IllegalArgumentException("Invalid value for cryptogram. Length must be greater than or equal to 1.");
    }
    this.cryptogram = cryptogram;
  }


  public ApplePayPaymentData eciIndicator(String eciIndicator) {
    
    
    if (eciIndicator != null && eciIndicator.length() < 1) {
      throw new IllegalArgumentException("Invalid value for eciIndicator. Length must be greater than or equal to 1.");
    }
    
    this.eciIndicator = eciIndicator;
    return this;
  }

   /**
   * ECI indicator, as defined by 3- Secure. The pattern is defined by an external party and supports Unicode.
   * @return eciIndicator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ECI indicator, as defined by 3- Secure. The pattern is defined by an external party and supports Unicode.")

  public String getEciIndicator() {
    return eciIndicator;
  }


  public void setEciIndicator(String eciIndicator) {
    
    
    if (eciIndicator != null && eciIndicator.length() < 1) {
      throw new IllegalArgumentException("Invalid value for eciIndicator. Length must be greater than or equal to 1.");
    }
    this.eciIndicator = eciIndicator;
  }


  public ApplePayPaymentData emvData(String emvData) {
    
    
    if (emvData != null && emvData.length() < 1) {
      throw new IllegalArgumentException("Invalid value for emvData. Length must be greater than or equal to 1.");
    }
    
    this.emvData = emvData;
    return this;
  }

   /**
   * Encoded Apple Pay EMV Payment Structure used for payments in China. The pattern is defined by an external party and supports Unicode.
   * @return emvData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Encoded Apple Pay EMV Payment Structure used for payments in China. The pattern is defined by an external party and supports Unicode.")

  public String getEmvData() {
    return emvData;
  }


  public void setEmvData(String emvData) {
    
    
    if (emvData != null && emvData.length() < 1) {
      throw new IllegalArgumentException("Invalid value for emvData. Length must be greater than or equal to 1.");
    }
    this.emvData = emvData;
  }


  public ApplePayPaymentData pin(String pin) {
    
    
    if (pin != null && pin.length() < 1) {
      throw new IllegalArgumentException("Invalid value for pin. Length must be greater than or equal to 1.");
    }
    
    this.pin = pin;
    return this;
  }

   /**
   * Bank Key encrypted Apple Pay PIN. The pattern is defined by an external party and supports Unicode.
   * @return pin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Bank Key encrypted Apple Pay PIN. The pattern is defined by an external party and supports Unicode.")

  public String getPin() {
    return pin;
  }


  public void setPin(String pin) {
    
    
    if (pin != null && pin.length() < 1) {
      throw new IllegalArgumentException("Invalid value for pin. Length must be greater than or equal to 1.");
    }
    this.pin = pin;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ApplePayPaymentData instance itself
   */
  public ApplePayPaymentData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplePayPaymentData applePayPaymentData = (ApplePayPaymentData) o;
    return Objects.equals(this.cryptogram, applePayPaymentData.cryptogram) &&
        Objects.equals(this.eciIndicator, applePayPaymentData.eciIndicator) &&
        Objects.equals(this.emvData, applePayPaymentData.emvData) &&
        Objects.equals(this.pin, applePayPaymentData.pin)&&
        Objects.equals(this.additionalProperties, applePayPaymentData.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cryptogram, eciIndicator, emvData, pin, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplePayPaymentData {\n");
    sb.append("    cryptogram: ").append(toIndentedString(cryptogram)).append("\n");
    sb.append("    eciIndicator: ").append(toIndentedString(eciIndicator)).append("\n");
    sb.append("    emvData: ").append(toIndentedString(emvData)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cryptogram");
    openapiFields.add("eci_indicator");
    openapiFields.add("emv_data");
    openapiFields.add("pin");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ApplePayPaymentData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ApplePayPaymentData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApplePayPaymentData is not found in the empty JSON string", ApplePayPaymentData.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("cryptogram") != null && !jsonObj.get("cryptogram").isJsonNull()) && !jsonObj.get("cryptogram").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cryptogram` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cryptogram").toString()));
      }
      if ((jsonObj.get("eci_indicator") != null && !jsonObj.get("eci_indicator").isJsonNull()) && !jsonObj.get("eci_indicator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eci_indicator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eci_indicator").toString()));
      }
      if ((jsonObj.get("emv_data") != null && !jsonObj.get("emv_data").isJsonNull()) && !jsonObj.get("emv_data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emv_data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emv_data").toString()));
      }
      if ((jsonObj.get("pin") != null && !jsonObj.get("pin").isJsonNull()) && !jsonObj.get("pin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pin").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApplePayPaymentData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApplePayPaymentData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApplePayPaymentData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApplePayPaymentData.class));

       return (TypeAdapter<T>) new TypeAdapter<ApplePayPaymentData>() {
           @Override
           public void write(JsonWriter out, ApplePayPaymentData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ApplePayPaymentData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ApplePayPaymentData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApplePayPaymentData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApplePayPaymentData
  * @throws IOException if the JSON string is invalid with respect to ApplePayPaymentData
  */
  public static ApplePayPaymentData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApplePayPaymentData.class);
  }

 /**
  * Convert an instance of ApplePayPaymentData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

