/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LiabilityShift;
import com.konfigthis.client.model.ThreeDSecureAuthenticationResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Results of Authentication such as 3D Secure.
 */
@ApiModel(description = "Results of Authentication such as 3D Secure.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AuthenticationResponse {
  public static final String SERIALIZED_NAME_LIABILITY_SHIFT = "liability_shift";
  @SerializedName(SERIALIZED_NAME_LIABILITY_SHIFT)
  private LiabilityShift liabilityShift;

  public static final String SERIALIZED_NAME_THREE_D_SECURE = "three_d_secure";
  @SerializedName(SERIALIZED_NAME_THREE_D_SECURE)
  private ThreeDSecureAuthenticationResponse threeDSecure;

  public static final String SERIALIZED_NAME_AUTHENTICATION_FLOW = "authentication_flow";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_FLOW)
  private Object authenticationFlow = null;

  public static final String SERIALIZED_NAME_EXEMPTION_DETAILS = "exemption_details";
  @SerializedName(SERIALIZED_NAME_EXEMPTION_DETAILS)
  private Object exemptionDetails = null;

  public AuthenticationResponse() {
  }

  public AuthenticationResponse liabilityShift(LiabilityShift liabilityShift) {
    
    
    
    
    this.liabilityShift = liabilityShift;
    return this;
  }

   /**
   * Get liabilityShift
   * @return liabilityShift
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LiabilityShift getLiabilityShift() {
    return liabilityShift;
  }


  public void setLiabilityShift(LiabilityShift liabilityShift) {
    
    
    
    this.liabilityShift = liabilityShift;
  }


  public AuthenticationResponse threeDSecure(ThreeDSecureAuthenticationResponse threeDSecure) {
    
    
    
    
    this.threeDSecure = threeDSecure;
    return this;
  }

   /**
   * Get threeDSecure
   * @return threeDSecure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ThreeDSecureAuthenticationResponse getThreeDSecure() {
    return threeDSecure;
  }


  public void setThreeDSecure(ThreeDSecureAuthenticationResponse threeDSecure) {
    
    
    
    this.threeDSecure = threeDSecure;
  }


  public AuthenticationResponse authenticationFlow(Object authenticationFlow) {
    
    
    
    
    this.authenticationFlow = authenticationFlow;
    return this;
  }

   /**
   * Get authenticationFlow
   * @return authenticationFlow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAuthenticationFlow() {
    return authenticationFlow;
  }


  public void setAuthenticationFlow(Object authenticationFlow) {
    
    
    
    this.authenticationFlow = authenticationFlow;
  }


  public AuthenticationResponse exemptionDetails(Object exemptionDetails) {
    
    
    
    
    this.exemptionDetails = exemptionDetails;
    return this;
  }

   /**
   * Get exemptionDetails
   * @return exemptionDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getExemptionDetails() {
    return exemptionDetails;
  }


  public void setExemptionDetails(Object exemptionDetails) {
    
    
    
    this.exemptionDetails = exemptionDetails;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AuthenticationResponse instance itself
   */
  public AuthenticationResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationResponse authenticationResponse = (AuthenticationResponse) o;
    return Objects.equals(this.liabilityShift, authenticationResponse.liabilityShift) &&
        Objects.equals(this.threeDSecure, authenticationResponse.threeDSecure) &&
        Objects.equals(this.authenticationFlow, authenticationResponse.authenticationFlow) &&
        Objects.equals(this.exemptionDetails, authenticationResponse.exemptionDetails)&&
        Objects.equals(this.additionalProperties, authenticationResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(liabilityShift, threeDSecure, authenticationFlow, exemptionDetails, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationResponse {\n");
    sb.append("    liabilityShift: ").append(toIndentedString(liabilityShift)).append("\n");
    sb.append("    threeDSecure: ").append(toIndentedString(threeDSecure)).append("\n");
    sb.append("    authenticationFlow: ").append(toIndentedString(authenticationFlow)).append("\n");
    sb.append("    exemptionDetails: ").append(toIndentedString(exemptionDetails)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("liability_shift");
    openapiFields.add("three_d_secure");
    openapiFields.add("authentication_flow");
    openapiFields.add("exemption_details");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AuthenticationResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AuthenticationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AuthenticationResponse is not found in the empty JSON string", AuthenticationResponse.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `three_d_secure`
      if (jsonObj.get("three_d_secure") != null && !jsonObj.get("three_d_secure").isJsonNull()) {
        ThreeDSecureAuthenticationResponse.validateJsonObject(jsonObj.getAsJsonObject("three_d_secure"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthenticationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthenticationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthenticationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthenticationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthenticationResponse>() {
           @Override
           public void write(JsonWriter out, AuthenticationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthenticationResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AuthenticationResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AuthenticationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AuthenticationResponse
  * @throws IOException if the JSON string is invalid with respect to AuthenticationResponse
  */
  public static AuthenticationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthenticationResponse.class);
  }

 /**
  * Convert an instance of AuthenticationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

