/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AuthenticationResponse;
import com.konfigthis.client.model.BinDetails;
import com.konfigthis.client.model.CardAttributesResponse;
import com.konfigthis.client.model.CardBrand;
import com.konfigthis.client.model.CardFromRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The payment card to use to fund a payment. Card can be a credit or debit card.
 */
@ApiModel(description = "The payment card to use to fund a payment. Card can be a credit or debit card.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CardResponse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LAST_DIGITS = "last_digits";
  @SerializedName(SERIALIZED_NAME_LAST_DIGITS)
  private String lastDigits;

  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  private CardBrand brand;

  public static final String SERIALIZED_NAME_AVAILABLE_NETWORKS = "available_networks";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_NETWORKS)
  private List<CardBrand> availableNetworks = null;

  /**
   * The payment card type.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
 public enum TypeEnum {
    CREDIT("CREDIT"),
    
    DEBIT("DEBIT"),
    
    PREPAID("PREPAID"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_AUTHENTICATION_RESULT = "authentication_result";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_RESULT)
  private AuthenticationResponse authenticationResult;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private CardAttributesResponse attributes;

  public static final String SERIALIZED_NAME_FROM_REQUEST = "from_request";
  @SerializedName(SERIALIZED_NAME_FROM_REQUEST)
  private CardFromRequest fromRequest;

  public static final String SERIALIZED_NAME_EXPIRY = "expiry";
  @SerializedName(SERIALIZED_NAME_EXPIRY)
  private String expiry;

  public static final String SERIALIZED_NAME_BIN_DETAILS = "bin_details";
  @SerializedName(SERIALIZED_NAME_BIN_DETAILS)
  private BinDetails binDetails;

  public CardResponse() {
  }

  
  public CardResponse(
     String lastDigits, 
     List<CardBrand> availableNetworks, 
     TypeEnum type
  ) {
    this();
    this.lastDigits = lastDigits;
    this.availableNetworks = availableNetworks;
    this.type = type;
  }

  public CardResponse name(String name) {
    
    
    if (name != null && name.length() < 2) {
      throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 2.");
    }
    
    this.name = name;
    return this;
  }

   /**
   * The card holder&#39;s name as it appears on the card.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The card holder's name as it appears on the card.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    if (name != null && name.length() < 2) {
      throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 2.");
    }
    this.name = name;
  }


   /**
   * The last digits of the payment card.
   * @return lastDigits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last digits of the payment card.")

  public String getLastDigits() {
    return lastDigits;
  }




  public CardResponse brand(CardBrand brand) {
    
    
    
    
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardBrand getBrand() {
    return brand;
  }


  public void setBrand(CardBrand brand) {
    
    
    
    this.brand = brand;
  }


   /**
   * Array of brands or networks associated with the card.
   * @return availableNetworks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Array of brands or networks associated with the card.")

  public List<CardBrand> getAvailableNetworks() {
    return availableNetworks;
  }




   /**
   * The payment card type.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The payment card type.")

  public TypeEnum getType() {
    return type;
  }




  public CardResponse authenticationResult(AuthenticationResponse authenticationResult) {
    
    
    
    
    this.authenticationResult = authenticationResult;
    return this;
  }

   /**
   * Get authenticationResult
   * @return authenticationResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AuthenticationResponse getAuthenticationResult() {
    return authenticationResult;
  }


  public void setAuthenticationResult(AuthenticationResponse authenticationResult) {
    
    
    
    this.authenticationResult = authenticationResult;
  }


  public CardResponse attributes(CardAttributesResponse attributes) {
    
    
    
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardAttributesResponse getAttributes() {
    return attributes;
  }


  public void setAttributes(CardAttributesResponse attributes) {
    
    
    
    this.attributes = attributes;
  }


  public CardResponse fromRequest(CardFromRequest fromRequest) {
    
    
    
    
    this.fromRequest = fromRequest;
    return this;
  }

   /**
   * Get fromRequest
   * @return fromRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CardFromRequest getFromRequest() {
    return fromRequest;
  }


  public void setFromRequest(CardFromRequest fromRequest) {
    
    
    
    this.fromRequest = fromRequest;
  }


  public CardResponse expiry(String expiry) {
    
    
    if (expiry != null && expiry.length() < 7) {
      throw new IllegalArgumentException("Invalid value for expiry. Length must be greater than or equal to 7.");
    }
    
    this.expiry = expiry;
    return this;
  }

   /**
   * The year and month, in ISO-8601 &#x60;YYYY-MM&#x60; date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   * @return expiry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).")

  public String getExpiry() {
    return expiry;
  }


  public void setExpiry(String expiry) {
    
    
    if (expiry != null && expiry.length() < 7) {
      throw new IllegalArgumentException("Invalid value for expiry. Length must be greater than or equal to 7.");
    }
    this.expiry = expiry;
  }


  public CardResponse binDetails(BinDetails binDetails) {
    
    
    
    
    this.binDetails = binDetails;
    return this;
  }

   /**
   * Get binDetails
   * @return binDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BinDetails getBinDetails() {
    return binDetails;
  }


  public void setBinDetails(BinDetails binDetails) {
    
    
    
    this.binDetails = binDetails;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CardResponse instance itself
   */
  public CardResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardResponse cardResponse = (CardResponse) o;
    return Objects.equals(this.name, cardResponse.name) &&
        Objects.equals(this.lastDigits, cardResponse.lastDigits) &&
        Objects.equals(this.brand, cardResponse.brand) &&
        Objects.equals(this.availableNetworks, cardResponse.availableNetworks) &&
        Objects.equals(this.type, cardResponse.type) &&
        Objects.equals(this.authenticationResult, cardResponse.authenticationResult) &&
        Objects.equals(this.attributes, cardResponse.attributes) &&
        Objects.equals(this.fromRequest, cardResponse.fromRequest) &&
        Objects.equals(this.expiry, cardResponse.expiry) &&
        Objects.equals(this.binDetails, cardResponse.binDetails)&&
        Objects.equals(this.additionalProperties, cardResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, lastDigits, brand, availableNetworks, type, authenticationResult, attributes, fromRequest, expiry, binDetails, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lastDigits: ").append(toIndentedString(lastDigits)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    availableNetworks: ").append(toIndentedString(availableNetworks)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    authenticationResult: ").append(toIndentedString(authenticationResult)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    fromRequest: ").append(toIndentedString(fromRequest)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    binDetails: ").append(toIndentedString(binDetails)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("last_digits");
    openapiFields.add("brand");
    openapiFields.add("available_networks");
    openapiFields.add("type");
    openapiFields.add("authentication_result");
    openapiFields.add("attributes");
    openapiFields.add("from_request");
    openapiFields.add("expiry");
    openapiFields.add("bin_details");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CardResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CardResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CardResponse is not found in the empty JSON string", CardResponse.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("last_digits") != null && !jsonObj.get("last_digits").isJsonNull()) && !jsonObj.get("last_digits").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_digits` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_digits").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("available_networks") != null && !jsonObj.get("available_networks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_networks` to be an array in the JSON string but got `%s`", jsonObj.get("available_networks").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `authentication_result`
      if (jsonObj.get("authentication_result") != null && !jsonObj.get("authentication_result").isJsonNull()) {
        AuthenticationResponse.validateJsonObject(jsonObj.getAsJsonObject("authentication_result"));
      }
      // validate the optional field `attributes`
      if (jsonObj.get("attributes") != null && !jsonObj.get("attributes").isJsonNull()) {
        CardAttributesResponse.validateJsonObject(jsonObj.getAsJsonObject("attributes"));
      }
      // validate the optional field `from_request`
      if (jsonObj.get("from_request") != null && !jsonObj.get("from_request").isJsonNull()) {
        CardFromRequest.validateJsonObject(jsonObj.getAsJsonObject("from_request"));
      }
      if ((jsonObj.get("expiry") != null && !jsonObj.get("expiry").isJsonNull()) && !jsonObj.get("expiry").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiry` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiry").toString()));
      }
      // validate the optional field `bin_details`
      if (jsonObj.get("bin_details") != null && !jsonObj.get("bin_details").isJsonNull()) {
        BinDetails.validateJsonObject(jsonObj.getAsJsonObject("bin_details"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CardResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CardResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CardResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CardResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CardResponse>() {
           @Override
           public void write(JsonWriter out, CardResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CardResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CardResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CardResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CardResponse
  * @throws IOException if the JSON string is invalid with respect to CardResponse
  */
  public static CardResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CardResponse.class);
  }

 /**
  * Convert an instance of CardResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

