/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Electronic Commerce Indicator (ECI). The ECI value is part of the 2 data elements that indicate the transaction was processed electronically. This should be passed on the authorization transaction to the Gateway/Processor.
 */
@JsonAdapter(EciFlag.Adapter.class)public enum EciFlag {
  
  MASTERCARD_NON_3D_SECURE_TRANSACTION("MASTERCARD_NON_3D_SECURE_TRANSACTION"),
  
  MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION("MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION"),
  
  MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION("MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION"),
  
  FULLY_AUTHENTICATED_TRANSACTION("FULLY_AUTHENTICATED_TRANSACTION"),
  
  ATTEMPTED_AUTHENTICATION_TRANSACTION("ATTEMPTED_AUTHENTICATION_TRANSACTION"),
  
  NON_3D_SECURE_TRANSACTION("NON_3D_SECURE_TRANSACTION");

  private String value;

  EciFlag(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EciFlag fromValue(String value) {
    for (EciFlag b : EciFlag.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EciFlag> {
    @Override
    public void write(final JsonWriter jsonWriter, final EciFlag enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EciFlag read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EciFlag.fromValue(value);
    }
  }
}

