/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EciFlag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The Third Party Network token used to fund a payment.
 */
@ApiModel(description = "The Third Party Network token used to fund a payment.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class NetworkTokenRequest {
  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  private String number;

  public static final String SERIALIZED_NAME_EXPIRY = "expiry";
  @SerializedName(SERIALIZED_NAME_EXPIRY)
  private String expiry;

  public static final String SERIALIZED_NAME_CRYPTOGRAM = "cryptogram";
  @SerializedName(SERIALIZED_NAME_CRYPTOGRAM)
  private String cryptogram;

  public static final String SERIALIZED_NAME_ECI_FLAG = "eci_flag";
  @SerializedName(SERIALIZED_NAME_ECI_FLAG)
  private EciFlag eciFlag;

  public static final String SERIALIZED_NAME_TOKEN_REQUESTOR_ID = "token_requestor_id";
  @SerializedName(SERIALIZED_NAME_TOKEN_REQUESTOR_ID)
  private String tokenRequestorId;

  public NetworkTokenRequest() {
  }

  public NetworkTokenRequest number(String number) {
    
    
    if (number != null && number.length() < 13) {
      throw new IllegalArgumentException("Invalid value for number. Length must be greater than or equal to 13.");
    }
    
    this.number = number;
    return this;
  }

   /**
   * Third party network token number.
   * @return number
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Third party network token number.")

  public String getNumber() {
    return number;
  }


  public void setNumber(String number) {
    
    
    if (number != null && number.length() < 13) {
      throw new IllegalArgumentException("Invalid value for number. Length must be greater than or equal to 13.");
    }
    this.number = number;
  }


  public NetworkTokenRequest expiry(String expiry) {
    
    
    if (expiry != null && expiry.length() < 7) {
      throw new IllegalArgumentException("Invalid value for expiry. Length must be greater than or equal to 7.");
    }
    
    this.expiry = expiry;
    return this;
  }

   /**
   * The year and month, in ISO-8601 &#x60;YYYY-MM&#x60; date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   * @return expiry
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).")

  public String getExpiry() {
    return expiry;
  }


  public void setExpiry(String expiry) {
    
    
    if (expiry != null && expiry.length() < 7) {
      throw new IllegalArgumentException("Invalid value for expiry. Length must be greater than or equal to 7.");
    }
    this.expiry = expiry;
  }


  public NetworkTokenRequest cryptogram(String cryptogram) {
    
    
    if (cryptogram != null && cryptogram.length() < 28) {
      throw new IllegalArgumentException("Invalid value for cryptogram. Length must be greater than or equal to 28.");
    }
    
    this.cryptogram = cryptogram;
    return this;
  }

   /**
   * An Encrypted one-time use value that&#39;s sent along with Network Token. This field is not required to be present for recurring transactions.
   * @return cryptogram
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An Encrypted one-time use value that's sent along with Network Token. This field is not required to be present for recurring transactions.")

  public String getCryptogram() {
    return cryptogram;
  }


  public void setCryptogram(String cryptogram) {
    
    
    if (cryptogram != null && cryptogram.length() < 28) {
      throw new IllegalArgumentException("Invalid value for cryptogram. Length must be greater than or equal to 28.");
    }
    this.cryptogram = cryptogram;
  }


  public NetworkTokenRequest eciFlag(EciFlag eciFlag) {
    
    
    
    
    this.eciFlag = eciFlag;
    return this;
  }

   /**
   * Get eciFlag
   * @return eciFlag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EciFlag getEciFlag() {
    return eciFlag;
  }


  public void setEciFlag(EciFlag eciFlag) {
    
    
    
    this.eciFlag = eciFlag;
  }


  public NetworkTokenRequest tokenRequestorId(String tokenRequestorId) {
    
    
    if (tokenRequestorId != null && tokenRequestorId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for tokenRequestorId. Length must be greater than or equal to 1.");
    }
    
    this.tokenRequestorId = tokenRequestorId;
    return this;
  }

   /**
   * A TRID, or a Token Requestor ID, is an identifier used by merchants to request network tokens from card networks. A TRID is a precursor to obtaining a network token for a credit card primary account number (PAN), and will aid in enabling secure card on file (COF) payments and reducing fraud.
   * @return tokenRequestorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A TRID, or a Token Requestor ID, is an identifier used by merchants to request network tokens from card networks. A TRID is a precursor to obtaining a network token for a credit card primary account number (PAN), and will aid in enabling secure card on file (COF) payments and reducing fraud.")

  public String getTokenRequestorId() {
    return tokenRequestorId;
  }


  public void setTokenRequestorId(String tokenRequestorId) {
    
    
    if (tokenRequestorId != null && tokenRequestorId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for tokenRequestorId. Length must be greater than or equal to 1.");
    }
    this.tokenRequestorId = tokenRequestorId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the NetworkTokenRequest instance itself
   */
  public NetworkTokenRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkTokenRequest networkTokenRequest = (NetworkTokenRequest) o;
    return Objects.equals(this.number, networkTokenRequest.number) &&
        Objects.equals(this.expiry, networkTokenRequest.expiry) &&
        Objects.equals(this.cryptogram, networkTokenRequest.cryptogram) &&
        Objects.equals(this.eciFlag, networkTokenRequest.eciFlag) &&
        Objects.equals(this.tokenRequestorId, networkTokenRequest.tokenRequestorId)&&
        Objects.equals(this.additionalProperties, networkTokenRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, expiry, cryptogram, eciFlag, tokenRequestorId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkTokenRequest {\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    cryptogram: ").append(toIndentedString(cryptogram)).append("\n");
    sb.append("    eciFlag: ").append(toIndentedString(eciFlag)).append("\n");
    sb.append("    tokenRequestorId: ").append(toIndentedString(tokenRequestorId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("number");
    openapiFields.add("expiry");
    openapiFields.add("cryptogram");
    openapiFields.add("eci_flag");
    openapiFields.add("token_requestor_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("number");
    openapiRequiredFields.add("expiry");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to NetworkTokenRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!NetworkTokenRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NetworkTokenRequest is not found in the empty JSON string", NetworkTokenRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NetworkTokenRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("number").toString()));
      }
      if (!jsonObj.get("expiry").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiry` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiry").toString()));
      }
      if ((jsonObj.get("cryptogram") != null && !jsonObj.get("cryptogram").isJsonNull()) && !jsonObj.get("cryptogram").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cryptogram` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cryptogram").toString()));
      }
      if ((jsonObj.get("token_requestor_id") != null && !jsonObj.get("token_requestor_id").isJsonNull()) && !jsonObj.get("token_requestor_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token_requestor_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_requestor_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NetworkTokenRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NetworkTokenRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NetworkTokenRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NetworkTokenRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<NetworkTokenRequest>() {
           @Override
           public void write(JsonWriter out, NetworkTokenRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public NetworkTokenRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             NetworkTokenRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NetworkTokenRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NetworkTokenRequest
  * @throws IOException if the JSON string is invalid with respect to NetworkTokenRequest
  */
  public static NetworkTokenRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NetworkTokenRequest.class);
  }

 /**
  * Convert an instance of NetworkTokenRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

