/*
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Customizes the buyer experience during the approval process for payment with Venmo.&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt; Partners and Marketplaces might configure &lt;code&gt;shipping_preference&lt;/code&gt; during partner account setup, which overrides the request values.&lt;/blockquote&gt;
 */
@ApiModel(description = "Customizes the buyer experience during the approval process for payment with Venmo.<blockquote><strong>Note:</strong> Partners and Marketplaces might configure <code>shipping_preference</code> during partner account setup, which overrides the request values.</blockquote>")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class VenmoWalletExperienceContext {
  public static final String SERIALIZED_NAME_BRAND_NAME = "brand_name";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  private String brandName;

  /**
   * The location from which the shipping address is derived.
   */
  @JsonAdapter(ShippingPreferenceEnum.Adapter.class)
 public enum ShippingPreferenceEnum {
    GET_FROM_FILE("GET_FROM_FILE"),
    
    NO_SHIPPING("NO_SHIPPING"),
    
    SET_PROVIDED_ADDRESS("SET_PROVIDED_ADDRESS");

    private String value;

    ShippingPreferenceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ShippingPreferenceEnum fromValue(String value) {
      for (ShippingPreferenceEnum b : ShippingPreferenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ShippingPreferenceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ShippingPreferenceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ShippingPreferenceEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ShippingPreferenceEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SHIPPING_PREFERENCE = "shipping_preference";
  @SerializedName(SERIALIZED_NAME_SHIPPING_PREFERENCE)
  private ShippingPreferenceEnum shippingPreference = ShippingPreferenceEnum.GET_FROM_FILE;

  public VenmoWalletExperienceContext() {
  }

  public VenmoWalletExperienceContext brandName(String brandName) {
    
    
    if (brandName != null && brandName.length() < 1) {
      throw new IllegalArgumentException("Invalid value for brandName. Length must be greater than or equal to 1.");
    }
    
    this.brandName = brandName;
    return this;
  }

   /**
   * The business name of the merchant. The pattern is defined by an external party and supports Unicode.
   * @return brandName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The business name of the merchant. The pattern is defined by an external party and supports Unicode.")

  public String getBrandName() {
    return brandName;
  }


  public void setBrandName(String brandName) {
    
    
    if (brandName != null && brandName.length() < 1) {
      throw new IllegalArgumentException("Invalid value for brandName. Length must be greater than or equal to 1.");
    }
    this.brandName = brandName;
  }


  public VenmoWalletExperienceContext shippingPreference(ShippingPreferenceEnum shippingPreference) {
    
    
    if (shippingPreference != null && shippingPreference.length() < 1) {
      throw new IllegalArgumentException("Invalid value for shippingPreference. Length must be greater than or equal to 1.");
    }
    
    this.shippingPreference = shippingPreference;
    return this;
  }

   /**
   * The location from which the shipping address is derived.
   * @return shippingPreference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GET_FROM_FILE", value = "The location from which the shipping address is derived.")

  public ShippingPreferenceEnum getShippingPreference() {
    return shippingPreference;
  }


  public void setShippingPreference(ShippingPreferenceEnum shippingPreference) {
    
    
    if (shippingPreference != null && shippingPreference.length() < 1) {
      throw new IllegalArgumentException("Invalid value for shippingPreference. Length must be greater than or equal to 1.");
    }
    this.shippingPreference = shippingPreference;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the VenmoWalletExperienceContext instance itself
   */
  public VenmoWalletExperienceContext putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VenmoWalletExperienceContext venmoWalletExperienceContext = (VenmoWalletExperienceContext) o;
    return Objects.equals(this.brandName, venmoWalletExperienceContext.brandName) &&
        Objects.equals(this.shippingPreference, venmoWalletExperienceContext.shippingPreference)&&
        Objects.equals(this.additionalProperties, venmoWalletExperienceContext.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brandName, shippingPreference, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VenmoWalletExperienceContext {\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    shippingPreference: ").append(toIndentedString(shippingPreference)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("brand_name");
    openapiFields.add("shipping_preference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VenmoWalletExperienceContext
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!VenmoWalletExperienceContext.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VenmoWalletExperienceContext is not found in the empty JSON string", VenmoWalletExperienceContext.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("brand_name") != null && !jsonObj.get("brand_name").isJsonNull()) && !jsonObj.get("brand_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brand_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brand_name").toString()));
      }
      if ((jsonObj.get("shipping_preference") != null && !jsonObj.get("shipping_preference").isJsonNull()) && !jsonObj.get("shipping_preference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shipping_preference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shipping_preference").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VenmoWalletExperienceContext.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VenmoWalletExperienceContext' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VenmoWalletExperienceContext> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VenmoWalletExperienceContext.class));

       return (TypeAdapter<T>) new TypeAdapter<VenmoWalletExperienceContext>() {
           @Override
           public void write(JsonWriter out, VenmoWalletExperienceContext value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public VenmoWalletExperienceContext read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             VenmoWalletExperienceContext instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VenmoWalletExperienceContext given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VenmoWalletExperienceContext
  * @throws IOException if the JSON string is invalid with respect to VenmoWalletExperienceContext
  */
  public static VenmoWalletExperienceContext fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VenmoWalletExperienceContext.class);
  }

 /**
  * Convert an instance of VenmoWalletExperienceContext to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

